source 'https://rubygems.org'
gem 'sinatra'
gem 'thin'
gem 'httparty'
gem 'require_all'
gem 'hpricot'
gem 'cucumber'
gem 'huzzah', :git => 'https://github.com/manheim/huzzah.git'
gem 'rspec'
gem 'watir-webdriver'
gem 'pry'
gem 'pry-nav'
gem 'test-helpers'
gem 'sauce_whisk'
gem 'parallel_tests'

